2021-03-30 07:10:08,699 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:46]
2021-03-30 07:15:14,719 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:46]
2021-03-30 07:20:46,761 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:46]
2021-03-30 07:30:52,979 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:46]
2021-03-30 07:32:56,756 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:46]
2021-03-30 07:37:10,248 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:46]
2021-03-31 05:14:01,726 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:49]
2021-03-31 06:21:23,371 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:49]
2021-03-31 06:47:16,418 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:49]
2021-04-02 07:41:42,554 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:51]
2021-04-02 08:09:39,117 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:51]
2021-04-02 08:19:05,039 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:51]
2021-04-02 08:19:49,820 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:51]
2021-04-06 10:14:09,193 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:55]
2021-04-06 10:14:17,665 ERROR: Exception on / [GET] [in e:\data science\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\data science\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\data science\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\data science\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\data science\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\data science\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\data science\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\data science\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Data Science\microblog\app\routes.py", line 34, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2021-04-06 10:16:42,919 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:55]
2021-04-06 10:17:19,092 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:55]
2021-04-06 10:29:53,515 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:55]
2021-04-06 10:31:00,659 INFO: Microblog startup [in E:\Data Science\microblog\app\__init__.py:55]
